<h1><center>EXERCISE</center></h1>

Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,

1. Logistic Regression
2. SVM
3. Decision Tree
4. Random Forest

In [4]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [2]:
iris = load_iris()

## Logistic Regression

In [9]:
score_l = cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),iris.data,iris.target)
score_l

array([1.        , 0.96666667, 0.93333333, 0.9       , 1.        ])

In [12]:
np.average(score_l)

0.9600000000000002

## Decision Tree

In [10]:
score_d = cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
score_d

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [11]:
np.average(score_d)

0.9600000000000002

## Support Vector Machine (SVM)

In [14]:
score_svm = cross_val_score(SVC(), iris.data, iris.target)
score_svm

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [15]:
np.average(score_svm)

0.9666666666666666

## Random Forest

In [16]:
score_rf = cross_val_score(RandomForestClassifier(), iris.data, iris.target)
score_rf

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [17]:
np.average(score_rf)

0.96

**Best Score So Far Is From SVM : 0.9666666666666666**