<h1><center>Machine Learning With Python<br>Save And Load Trained Model</center></h1>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [4]:
model.coef_

array([135.78767123])

In [5]:
model.intercept_

180616.43835616432

In [8]:
model.predict([[5000]])

C:\Users\efekan\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [17]:
import pickle

In [18]:
with open('model_pickle', 'wb') as f:
    pickle.dump(model, f)

In [19]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [20]:
mp.predict([[5000]])

C:\Users\efekan\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [25]:
import joblib

In [26]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [27]:
mj = joblib.load('model_joblib')

In [28]:
mj.predict([[5000]])

C:\Users\efekan\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [29]:
mj.coef_

array([135.78767123])

In [30]:
mj.intercept_

180616.43835616432